namespace GameOfFates.Core
{
    using System.Collections.Generic;

    public static class Fates
    {
        public static List<string> LoadAnswers() => new List<string>
        {
            "Yes, definitely.",
            "No, certainly not.",
            "Maybe, time will tell.",
            "Ask again later.",
            "The signs point to yes.",
            "The outlook is not so good.",
            "It is certain.",
            "My sources say no.",
            "Very doubtful.",
            "Without a doubt.",
            "Better not tell you now.",
            "Yes, but be prepared.",
            "Unlikely, but possible.",
            "Concentrate and ask again.",
            "Yes, and it will be a blessing.",
            "No, and it might be for the best.",
            "Cannot predict now.",
            "Absolutely, without a doubt.",
            "The answer is unclear, try again.",
            "The stars say no.",
            "Yes, and with great success.",
            "No, and it’s a good thing.",
            "Perhaps in another life.",
            "The universe says yes.",
            "The odds are in your favor.",
            "Do not count on it.",
            "Signs point to no.",
            "Yes, if you believe.",
            "No, but don’t lose hope.",
            "It is highly likely.",
            "It is not in the cards.",
            "All indications say yes.",
            "Not in the foreseeable future.",
            "Yes, but not as expected.",
            "No, and you should be cautious.",
            "It's a mystery.",
            "Yes, the omens are good.",
            "No, the omens are bad.",
            "Yes, with conditions.",
            "No, under any circumstances.",
            "Yes, luck is on your side.",
            "No, fate has other plans.",
            "Maybe, but be patient.",
            "Definitely, but with a twist.",
            "No, and it’s a sign.",
            "The fates are undecided.",
            "Yes, fortune smiles upon you.",
            "No, misfortune lurks.",
            "Yes, the outcome is favorable.",
            "No, the outcome is unfavorable.",
            "Yes, it’s written in the stars.",
            "No, it’s written in the stars.",
            "Yes, beyond a shadow of a doubt.",
            "No, beyond a shadow of a doubt.",
            "Yes, and it will bring joy.",
            "No, and it will bring sorrow.",
            "Yes, but only if you act now.",
            "No, unless circumstances change.",
            "The spirits say yes.",
            "The spirits say no.",
            "Yes, with a stroke of luck.",
            "No, unless you’re lucky.",
            "Yes, but don’t take it for granted.",
            "No, but there’s hope.",
            "Yes, as sure as the sun will rise.",
            "No, as sure as the sun will set.",
            "Yes, but it won’t be easy.",
            "No, but there’s a silver lining.",
            "Yes, the path is clear.",
            "No, the path is blocked.",
            "Yes, the future looks bright.",
            "No, the future looks dim.",
            "Yes, and it will surprise you.",
            "No, and it will surprise you.",
            "Yes, it’s almost certain.",
            "No, it’s highly unlikely.",
            "Yes, with a bit of effort.",
            "No, despite your efforts.",
            "Yes, fate is on your side.",
            "No, fate is against you.",
            "Yes, the signs are auspicious.",
            "No, the signs are ominous.",
            "Yes, but only if you believe.",
            "No, unless you believe.",
            "Yes, the stars align.",
            "No, the stars misalign.",
            "Yes, it’s a strong possibility.",
            "No, it’s a weak possibility.",
            "Yes, and it will be worthwhile.",
            "No, and it will be challenging.",
            "Yes, with flying colors.",
            "No, but don’t despair.",
            "Yes, it’s highly probable.",
            "No, it’s highly improbable.",
            "Yes, the answer is affirmative.",
            "No, the answer is negative.",
            "Yes, and it’s a sure thing.",
            "No, and it’s a long shot.",
            "Yes, with all your heart.",
            "No, but keep the faith.",
        };
    }
}
